# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0002_auto_20180616_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
