# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0003_auto_20180617_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mics.Category'),
        ),
    ]
