# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0005_auto_20180617_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
