# Generated by Django 3.2.25 on 2026-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mics', '0008_auto_20260122_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
